<% common = "--format pretty -r src"%>

default   : --profile functional

functional:  --tags @tagone --out=profile-one.html <%= common %>
integration: --tags @tagtwo --out=profile-two.html <%= common %>