<% common = "--format pretty -r src"%>

default   : --profile functional --profile integration

functional:  --tags @functional   --out=reports/functional.html stub=true <%= common %>
integration: --tags @integration  --out=reports/integration.html <%= common %>