<% source = "./src/common"%>

<% common = "--format pretty -r #{source}"%>

functional        : --tags @functional  stub=true <%= common %>
functional-smoke  : --tags @functional --tags ~@regression --tags ~@core  stub=true <%= common %>
integration       : --tags @integration           <%= common %>
tags              :  <%= common %>