<% source = "./src/common"%>
<% pages  = ENV['pages']%>

<% common = "--format pretty -r #{source} pages=#{pages}"%>

default     : --profile functional --profile integration

functional  : --tags @functional  stub=true <%= common %>
integration : --tags @integration           <%= common %>
tags        :  <%= common %>