<% source = "./src/common"%>
<% smoke = "--tags ~@regression --tags ~@core"%>

<% common = "--format pretty -r #{source}"%>

functional        : --tags @functional  stub=true <%= common %>
functional-smoke  : --tags @functional  stub=true <%= common %>  <%= smoke %>
integration       : --tags @integration           <%= common %>
integration-smoke : --tags @integration           <%= common %> <%= smoke %>
tags              :  <%= common %>