<% source = "./src/common"%>
<% pages  = ENV['pages']%>

<% common = "--format pretty -r #{source} pages=#{pages}"%>

default     : --profile functional --profile integration

functional  :  --tags @functional   --out=reports/functional.html stub=true <%= common %>
integration : --tags @integration  --out=reports/integration.html <%= common %>
tags        : --out=reports/integration.html <%= common %>