<% common = "--format pretty "%>

default   : --profile profile-one

profile-one: FIG_NEWTON_FILE=one.yml  data="one" --tags @tagone --out=profile-one.html <%= common %>
profile-two: FIG_NEWTON_FILE=two.yml  data="two" --tags @tagtwo --out=profile-two.html <%= common %>