<% common = "--format pretty -r src"%>

default   : --profile functional

functional: FIG_NEWTON_FILE=one.yml  data="one" --tags @tagone --out=profile-one.html <%= common %>
integration: FIG_NEWTON_FILE=two.yml  data="two" --tags @tagtwo --out=profile-two.html <%= common %>