<% common = "--format pretty "%>

default   : --profile profile-one

profile-one: --tags @tagone --out=reports/profile-one.html <%= common %>
profile-two: --tags @tagtwo --out=reports/profile-two.html <%= common %>