<% common = "--format pretty -r src"%>

default   : --profile functional

functional:  --tags @functional   --out=functional.html <%= common %>
integration: --tags @integration  --out=integration.html <%= common %>