<% source = "./src/common"%>

<% common = "--format pretty -r #{source}"%>

functional  : --tags @functional  stub=true <%= common %>
integration : --tags @integration           <%= common %>
tags        :  <%= common %>