base_url: google.com
timeout: 300

data :
  default: config/data/default
  mobile: config/data/mobile

pages:
  default : ./src/bigweb/pages
  mobile  : ./src/mobile/pages

stub :
  wiremock :
    jar  : wiremock-standalone-2.3.1
    path : config/stub
    port : 8081
    root_dir : config/stub
    verbose : false

driver :
  browser: chrome
  device: Apple iPhone 5